export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SKIN_TEST_SUCCESS = "SKIN_TEST_SUCCESS";
export const SKIN_TEST_FAIL = "SKIN_TEST_FAIL";

export const PRODUCT_FETCH_ALL_SUCCESS = "PRODUCT_FETCH_ALL_SUCCESS";
export const PRODUCT_FETCH_ALL_FAIL = "PRODUCT_FETCH_ALL_FAIL";

export const PRODUCT_FETCH_TYPE_SUCCESS = "PRODUCT_FETCH_TYPE_SUCCESS";
export const PRODUCT_FETCH_TYPE_FAIL = "PRODUCT_FETCH_TYPE_FAIL";

export const SKIN_DIEASES_SUCCESS = "SKIN_DIEASES_SUCCESS";
export const SKIN_DIEASES_FAIL = "SKIN_DIEASES_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const SUBTRACT_QUANTITY = "SUBTRACT_QUANTITY";

export const CART_PRODUCT_FETCH_ALL = "CART_PRODUCT_FETCH_ALL";
export const CART_PRODUCT_FETCH_FAIL = "CART_PRODUCT_FETCH_FAIL";

export const CART_PRODUCT_PAYMENT_SUCCESS = "CART_PRODUCT_PAYMENT_SUCCESS";
export const CART_PRODUCT_PAYMENT_FAIL = "CART_PRODUCT_PAYMENT_FAIL";

export const REFRESH_PRODUCT_FLAG = "REFRESH_PRODUCT_FLAG";
