export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SKIN_TEST_SUCCESS = "SKIN_TEST_SUCCESS";
export const SKIN_TEST_FAIL = "SKIN_TEST_FAIL";

export const PRODUCT_FETCH_ALL_SUCCESS = "PRODUCT_FETCH_ALL_SUCCESS";
export const PRODUCT_FETCH_ALL_FAIL = "PRODUCT_FETCH_ALL_FAIL";

export const PRODUCT_FETCH_TYPE_SUCCESS = "PRODUCT_FETCH_TYPE_SUCCESS";
export const PRODUCT_FETCH_TYPE_FAIL = "PRODUCT_FETCH_TYPE_FAIL";

export const SKIN_DIEASES_SUCCESS = "SKIN_DIEASES_SUCCESS";
export const SKIN_DIEASES_FAIL = "SKIN_DIEASES_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const SUBTRACT_QUANTITY = "SUBTRACT_QUANTITY";

export const CART_PRODUCT_FETCH_ALL = "CART_PRODUCT_FETCH_ALL";
export const CART_PRODUCT_FETCH_FAIL = "CART_PRODUCT_FETCH_FAIL";

export const CART_PRODUCT_PAYMENT_SUCCESS = "CART_PRODUCT_PAYMENT_SUCCESS";
export const CART_PRODUCT_PAYMENT_FAIL = "CART_PRODUCT_PAYMENT_FAIL";

export const REFRESH_PRODUCT_FLAG = "REFRESH_PRODUCT_FLAG";

export const UPDATE_CLIENT_PROFILE_SUCCESS = "UPDATE_CLIENT_PROFILE_SUCCESS";
export const UPDATE_CLIENT_PROFILE_FAIL = "UPDATE_CLIENT_PROFILE_FAIL";

export const GET_LOGIN_DATA_SUCCESS = "GET_LOGIN_DATA_SUCCESS";

export const ORDER_PLACE_SUCCESS = "ORDER_PLACE_SUCCESS";
export const ORDER_PLACE_FAIL = "ORDER_PLACE_SUCCESS";

export const GET_CLIENT_ORDER_SUCCESS = "GET_CLIENT_ORDER_SUCCESS";

export const PENDING_PRODUCT_CHECKOUT_SUCCESS = "PENDING_PRODUCT_CHECKOUT_SUCCESS";
export const PENDING_PRODUCT_CHECKOUT_FAIL = "PENDING_PRODUCT_CHECKOUT_FAIL";

export const REFRESH_ORDER_FLAG = "REFRESH_ORDER_FLAG";

export const REFRESH_ORDER_RECIEPT = "REFRESH_ORDER_RECIEPT";

export const GET_CLIENT_UN_PAID_ORDER_SUCCESS = "GET_CLIENT_UN_PAID_ORDER_SUCCESS";

export const REMOVE_UNPIAD_DATA_SUCCESS = "REMOVE_UNPIAD_DATA_SUCCESS";

export const APPOINTMENT_USER_PAYMENT_SUCCESS = "APPOINTMENT_USER_PAYMENT_SUCCESS";
export const APPOINTMENT_USER_PAYMENT_FAIL = "APPOINTMENT_USER_PAYMENT_FAIL";

export const GET_USER_MEDICATION = "GET_USER_MEDICATION";